services:
  nginx:
    container_name: nginx
    image: nginx:1.27.0
    ports:
      - "9099:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - post_service

  nginxgrpc:
    container_name: nginxgrpc
    image: nginx:1.27.0
    ports:
      - "9098:80"
    volumes:
      - ./nginx-grpc.conf:/etc/nginx/nginx.conf
    networks:
      - post_service

  server1:
    container_name: server1
    build:
      context: ../server
      dockerfile: Dockerfile
    networks:
      - post_service
    environment:
      - GRPC_PORT=80

  server2:
    container_name: server2
    build:
      context: ../server
      dockerfile: Dockerfile
    networks:
      - post_service
    environment:
      - GRPC_PORT=80

  api-gateway: 
    container_name: api-gateway
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    networks:
      - post_service
    environment:
      - HTTP_PORT=80
      - POST_SERVICE_HOST=nginx
      - POST_SERVICE_PORT=80
    ports:
      - "5050:80"

  api-gateway-grpc-lb: 
    container_name: api-gateway-grpc-lb
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    networks:
      - post_service
    environment:
      - HTTP_PORT=80
      - POST_SERVICE_HOST=nginxgrpc
      - POST_SERVICE_PORT=80
    ports:
      - "5051:80"

networks:
  post_service:
    driver: bridge
